# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    # local hooks
    - repo: local
      hooks:
          - id: ruff
            name: ruff
            entry: poetry run ruff check --fix --exit-non-zero-on-fix --show-fixes
            language: system
            types: [python]
            require_serial: true
          - id: mypy
            name: mypy
            entry: poetry run mypy
            language: system
            types: [python]
            files: ^(renumics|scripts)/
            require_serial: true
          - id: dynamic-versioning
            name: dynamic-versioning
            language: system
            entry: poetry run scripts/check_dynamic_versioning.py
            files: pyproject.toml

    # "official" pre-commit hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
            exclude: \.secret\.
          - id: end-of-file-fixer
            exclude: \.secret\.
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-yaml
            exclude: (\.secret\.)|(^\.github/.*\.yml)
          - id: check-json
          - id: check-toml
          - id: check-symlinks

    # third-pary hooks
    - repo: https://github.com/psf/black
      rev: 24.1.1
      hooks:
          - id: black
          - id: black-jupyter
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            exclude: (\.secret\.)|(pnpm-lock.yaml)
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            files: src
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.28.0
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
          - id: shfmt
    - repo: https://github.com/kynan/nbstripout
      rev: 0.7.1
      hooks:
          - id: nbstripout
